"""speciality not null

Revision ID: 4e63dc830551
Revises: 689c2ce787c4
Create Date: 2025-04-02 15:39:03.322803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e63dc830551'
down_revision = '689c2ce787c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.alter_column('specialty',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.alter_column('specialty',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
