"""Add specialty to PlanOption

Revision ID: 689c2ce787c4
Revises: 5b72036df056
Create Date: 2025-04-02 15:07:50.908754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689c2ce787c4'
down_revision = '5b72036df056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_options', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
